-- Align persisted Hub role permissions with the versioned Core/Hub contract.
-- Older databases seeded OWNER/ADMIN with the permissions that existed at the
-- time of the original foundation migration. Newer organization and query
-- permissions must be backfilled explicitly so existing memberships do not
-- fail closed merely because their role predates the contract expansion.

insert into public.permissions (code, description)
values
  ('organization.read', 'View organization settings and profile'),
  ('organization.update', 'Update organization settings and profile'),
  ('organization.delete', 'Delete or archive an organization'),
  ('organization.ownership.transfer', 'Transfer organization ownership'),
  ('billing.manage', 'Manage organization billing'),
  ('member.invite', 'Invite organization members'),
  ('booking.manage', 'Manage booking operations'),
  ('kiosk.manage', 'Manage kiosk operations'),
  ('query.manage', 'Manage saved queries and query configuration'),
  ('query.import', 'Import query data'),
  ('query.bulk_edit', 'Run bulk query actions')
on conflict (code) do update set description = excluded.description;

insert into public.role_permissions (role_id, permission_code)
select roles.id, defaults.permission_code
from (
  values
    ('OWNER', 'organization.manage'),
    ('OWNER', 'organization.read'),
    ('OWNER', 'organization.update'),
    ('OWNER', 'organization.delete'),
    ('OWNER', 'organization.ownership.transfer'),
    ('OWNER', 'billing.manage'),
    ('OWNER', 'store.read'),
    ('OWNER', 'store.manage'),
    ('OWNER', 'store.create'),
    ('OWNER', 'store.delete'),
    ('OWNER', 'member.manage'),
    ('OWNER', 'member.invite'),
    ('OWNER', 'catalog.read'),
    ('OWNER', 'catalog.manage'),
    ('OWNER', 'order.read'),
    ('OWNER', 'order.create'),
    ('OWNER', 'payment.receive'),
    ('OWNER', 'refund.create'),
    ('OWNER', 'order.void'),
    ('OWNER', 'price.override'),
    ('OWNER', 'cash_drawer.open'),
    ('OWNER', 'integration.manage'),
    ('OWNER', 'audit.read'),
    ('OWNER', 'devices.manage'),
    ('OWNER', 'booking.manage'),
    ('OWNER', 'kiosk.manage'),
    ('OWNER', 'query.read'),
    ('OWNER', 'query.manage'),
    ('OWNER', 'query.import'),
    ('OWNER', 'query.export'),
    ('OWNER', 'query.bulk_edit'),
    ('ADMIN', 'organization.manage'),
    ('ADMIN', 'organization.read'),
    ('ADMIN', 'organization.update'),
    ('ADMIN', 'billing.manage'),
    ('ADMIN', 'store.read'),
    ('ADMIN', 'store.manage'),
    ('ADMIN', 'store.create'),
    ('ADMIN', 'store.delete'),
    ('ADMIN', 'member.manage'),
    ('ADMIN', 'member.invite'),
    ('ADMIN', 'catalog.read'),
    ('ADMIN', 'catalog.manage'),
    ('ADMIN', 'order.read'),
    ('ADMIN', 'order.create'),
    ('ADMIN', 'payment.receive'),
    ('ADMIN', 'refund.create'),
    ('ADMIN', 'order.void'),
    ('ADMIN', 'price.override'),
    ('ADMIN', 'cash_drawer.open'),
    ('ADMIN', 'integration.manage'),
    ('ADMIN', 'audit.read'),
    ('ADMIN', 'devices.manage'),
    ('ADMIN', 'booking.manage'),
    ('ADMIN', 'kiosk.manage'),
    ('ADMIN', 'query.read'),
    ('ADMIN', 'query.manage'),
    ('ADMIN', 'query.import'),
    ('ADMIN', 'query.export'),
    ('ADMIN', 'query.bulk_edit'),
    ('ORGANIZATION_MANAGER', 'organization.read'),
    ('ORGANIZATION_MANAGER', 'organization.update'),
    ('ORGANIZATION_MANAGER', 'organization.manage'),
    ('ORGANIZATION_MANAGER', 'store.read'),
    ('ORGANIZATION_MANAGER', 'store.create'),
    ('ORGANIZATION_MANAGER', 'store.manage'),
    ('ORGANIZATION_MANAGER', 'member.manage'),
    ('ORGANIZATION_MANAGER', 'member.invite'),
    ('ORGANIZATION_MANAGER', 'catalog.read'),
    ('ORGANIZATION_MANAGER', 'catalog.manage'),
    ('ORGANIZATION_MANAGER', 'order.read'),
    ('ORGANIZATION_MANAGER', 'audit.read'),
    ('ORGANIZATION_MANAGER', 'integration.manage'),
    ('ORGANIZATION_MANAGER', 'devices.manage'),
    ('ORGANIZATION_MANAGER', 'query.read'),
    ('ORGANIZATION_MANAGER', 'query.manage'),
    ('ORGANIZATION_MANAGER', 'query.import'),
    ('ORGANIZATION_MANAGER', 'query.export'),
    ('ORGANIZATION_MANAGER', 'query.bulk_edit'),
    ('BRANCH_MANAGER', 'store.read'),
    ('BRANCH_MANAGER', 'store.manage'),
    ('BRANCH_MANAGER', 'catalog.read'),
    ('BRANCH_MANAGER', 'catalog.manage'),
    ('BRANCH_MANAGER', 'order.read'),
    ('BRANCH_MANAGER', 'order.create'),
    ('BRANCH_MANAGER', 'payment.receive'),
    ('BRANCH_MANAGER', 'refund.create'),
    ('BRANCH_MANAGER', 'order.void'),
    ('BRANCH_MANAGER', 'price.override'),
    ('BRANCH_MANAGER', 'cash_drawer.open'),
    ('BRANCH_MANAGER', 'audit.read'),
    ('BRANCH_MANAGER', 'devices.manage'),
    ('BRANCH_MANAGER', 'member.manage'),
    ('BRANCH_MANAGER', 'member.invite'),
    ('BRANCH_MANAGER', 'query.read'),
    ('BRANCH_MANAGER', 'query.export'),
    ('STORE_MANAGER', 'store.read'),
    ('STORE_MANAGER', 'store.manage'),
    ('STORE_MANAGER', 'catalog.read'),
    ('STORE_MANAGER', 'catalog.manage'),
    ('STORE_MANAGER', 'order.read'),
    ('STORE_MANAGER', 'order.create'),
    ('STORE_MANAGER', 'payment.receive'),
    ('STORE_MANAGER', 'refund.create'),
    ('STORE_MANAGER', 'order.void'),
    ('STORE_MANAGER', 'price.override'),
    ('STORE_MANAGER', 'cash_drawer.open'),
    ('STORE_MANAGER', 'devices.manage'),
    ('STORE_MANAGER', 'audit.read'),
    ('STORE_MANAGER', 'member.manage'),
    ('STORE_MANAGER', 'member.invite'),
    ('STORE_MANAGER', 'booking.manage'),
    ('STORE_MANAGER', 'kiosk.manage'),
    ('STORE_MANAGER', 'query.read'),
    ('STORE_MANAGER', 'query.manage'),
    ('STORE_MANAGER', 'query.import'),
    ('STORE_MANAGER', 'query.export'),
    ('STORE_MANAGER', 'query.bulk_edit'),
    ('CASHIER', 'store.read'),
    ('CASHIER', 'catalog.read'),
    ('CASHIER', 'order.read'),
    ('CASHIER', 'order.create'),
    ('CASHIER', 'payment.receive'),
    ('CASHIER', 'cash_drawer.open'),
    ('CASHIER', 'query.read'),
    ('BOOKING_STAFF', 'store.read'),
    ('BOOKING_STAFF', 'order.read'),
    ('BOOKING_STAFF', 'order.create'),
    ('BOOKING_STAFF', 'booking.manage'),
    ('BOOKING_STAFF', 'query.read'),
    ('KIOSK_STAFF', 'store.read'),
    ('KIOSK_STAFF', 'catalog.read'),
    ('KIOSK_STAFF', 'order.read'),
    ('KIOSK_STAFF', 'kiosk.manage'),
    ('KIOSK_STAFF', 'query.read'),
    ('KITCHEN', 'store.read'),
    ('KITCHEN', 'order.read'),
    ('STAFF', 'store.read'),
    ('STAFF', 'catalog.read'),
    ('STAFF', 'order.read'),
    ('STAFF', 'order.create'),
    ('STAFF', 'query.read'),
    ('VIEWER', 'store.read'),
    ('VIEWER', 'order.read'),
    ('VIEWER', 'query.read')
) as defaults(role_code, permission_code)
join public.roles roles on roles.code = defaults.role_code
join public.permissions permissions on permissions.code = defaults.permission_code
on conflict (role_id, permission_code) do nothing;

insert into aevo_control_plane_migration_ledger
  (schema_name, table_name, semantic_domain, historical_migration_repos,
   current_owner, target_owner, runtime_writers, readers, current_write_mode,
   migration_phase, transition_state, delete_after)
values
  ('public', 'role_permissions', 'hub-authorization', '{aevo-hub}',
   'aevo-core-api', 'aevo-core-api', '{aevo-core-api}',
   '{aevo-core-api,aevo-hub,aevo-admin}', 'CORE_ONLY', 'CANONICAL', 'CANONICAL', null)
on conflict (schema_name, table_name) do update set
  semantic_domain = excluded.semantic_domain,
  historical_migration_repos = excluded.historical_migration_repos,
  current_owner = excluded.current_owner,
  target_owner = excluded.target_owner,
  runtime_writers = excluded.runtime_writers,
  readers = excluded.readers,
  current_write_mode = excluded.current_write_mode,
  migration_phase = excluded.migration_phase,
  transition_state = excluded.transition_state,
  delete_after = excluded.delete_after,
  updated_at = now();

comment on table public.role_permissions is 'Core-owned role permission assignments aligned by migration 0034; Hub reads the resolved projection only.';
